### ISSUE TITLE
Problems getting e-paper display to work

### ISSUE THREAD

**Issue by jolivr** [scidsg/pi-relay#10]
First of all, I am a complete beginner with tor and raspberry pi. However, using your script I was able to start a middle relay and monitor it with Nyx.

I then ordered the recommended Waveshare display, connected it via their docs and successfully ran their python demos. Next, I came back to this site and ran the e-paper setup script which appeared to run successfully and rebooted. Once I rebooted I started the tor service, verified it was up using Nyx, but the display has not shown any data. 

1.) Is there any special command to run once the Pi is rebooted to start the display?
2.) If not, do you have any tests/commands/logs that I can run to help me troubleshoot?

Thank you very much for Pi-Relay.. it is exactly what I needed to start my relay.

**Comment by jolivr** [comment]
After some research, I saw that the `/home/pi` directory wasn't created as well as the `.bashrc` and `relay-status.py`. I manually created the folder and re-ran the installer. The files were created then. After reboot, it seems that everything works now!

**Comment by glenn-sorrentino** [comment]
What version of the Raspberry Pi OS are you using? 

Any way that you can share a gist of the install progress? 

Sometimes it's easiest to start from scratch, too. First, run the install script, and when it's complete, just run display.sh to configure the display.

**Comment by glenn-sorrentino** [comment]
> After some research, I saw that the `/home/pi` directory wasn't created as well as the `.bashrc` and `relay-status.py`. I manually created the folder and re-ran the installer. The files were created then. I'm wondering if the installer creates files in the `/home` folder of `root` but I am logging in with my custom user I created during initial installation?

Hey just following up here. Any luck on the display?

**Comment by glenn-sorrentino** [comment]
@jolivr Closing since there's no response. I've confirmed functionality on a Pi 4 w/ the listed epaper display. Please let me know if you run into any other issues.
