### ISSUE TITLE
Eink Waveshare

### ISSUE THREAD

**Issue by g33k247** [scidsg/pi-relay#2]
Which 2.13-inch Eink Waveshare is Recommended?

**Comment by glenn-sorrentino** [comment]
Right now this this is the supported model:
https://www.waveshare.com/product/raspberry-pi/displays/e-paper/2.13inch-e-paper-hat.htm
https://www.amazon.com/gp/product/B07Z1WYRQH/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
